services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./laravel:/var/www/html
    environment:
      - APP_ENV=local
    expose:
      - "9000"

  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./laravel:/var/www/html:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
